alias agi='sudo apt-get install'
alias agu='sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias lal='ls -AlF'
alias la='ls -AF'
alias ll='ls -lF'
alias ls='ls --color=auto'
alias q='exit'
alias vdir='vdir --color=auto'
alias vpn=sudo'sudo openvpn --config'
